# Generated by Django 6.0 on 2025-12-07 23:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id_desc', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'descricao',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_end', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
                ('nome', models.CharField(blank=True, max_length=160, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(max_length=45)),
                ('municipio', models.CharField(blank=True, max_length=160, null=True)),
                ('bairro', models.CharField(blank=True, max_length=160, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('contato', models.CharField(blank=True, max_length=160, null=True)),
                ('email', models.EmailField(blank=True, max_length=160, null=True)),
                ('fone1', models.CharField(blank=True, max_length=15, null=True)),
                ('fone2', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'endereco',
                'ordering': ['municipio', 'bairro', 'endereco'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=160, null=True)),
                ('fone1', models.CharField(blank=True, max_length=15, null=True)),
                ('fone2', models.CharField(blank=True, max_length=15, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.endereco')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=120, null=True)),
                ('gancho', models.CharField(blank=True, max_length=45, null=True)),
                ('cor', models.CharField(blank=True, max_length=45, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(blank=True, max_length=45, null=True)),
                ('fone', models.CharField(blank=True, max_length=15, null=True)),
                ('previlegio', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_moderno',
                'ordering': ['user__username'],
            },
        ),
    ]
