# Generated by Django 6.0 on 2025-12-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descricao',
            options={'managed': False, 'ordering': ['descricao']},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'managed': False, 'ordering': ['municipio', 'bairro', 'endereco']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orcamento',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
